-- ============================================================================
-- Migration 007 — Phase 12.5 (partial): UDIN register + structured ARN
-- Target: the LIVE Praxida Supabase project (fwmmdyebvzncpezdwnxm).
-- Applied 2026-07-19 by Jay via the Supabase SQL editor (ran clean, no
-- errors); folded into schema.sql in the same commit that drafted this file.
-- Before applying, the exact RLS policies below were walked through with Jay
-- role-by-role to confirm client_user has no SELECT/INSERT/UPDATE/DELETE
-- path on udin_register (see the session transcript) — no changes were
-- needed as a result of that review.
--
-- Covers the first two thirds of docs/ROADMAP.md's Phase 12.5 ("Statutory
-- identifiers & migration on-ramp"): ARN/acknowledgment-number capture and
-- the UDIN register. The third item (bulk client import) is explicitly
-- OUT of scope for this migration/session — it needs no schema of its own
-- yet and mixing it in would violate the project's one-phase-per-session
-- rule; still tracked as an open Phase 12.5 checklist item in ROADMAP.md.
--
-- ----------------------------------------------------------------------------
-- Part A — tasks.arn / tasks.filed_date (structured filing outcome)
-- ----------------------------------------------------------------------------
-- Phase 10 already captures ARN + filed date on statutory-task completion,
-- but logs them into task_activities as a `filing_outcome_recorded` row
-- (project_context.md §4.8) — deliberately chosen then to avoid a migration.
-- That table is STAFF-ONLY readable by RLS ("Immutable audit log... clients
-- get their curated view from tasks/documents" — schema.sql §7.4/§11.18),
-- so an ARN captured that way can never reach the filing-status grid (which
-- reads `tasks` directly, not activities) or the client portal — exactly
-- the migration-002 checklist_items precedent (same file, same reasoning):
-- state a client or a grid must read cannot live in a staff-only-readable
-- audit table. Two plain, nullable columns on `tasks`, by contrast, are
-- already covered by the EXISTING tasks SELECT/UPDATE RLS policies (visible_
-- to_client-gated read for clients; assignee/department/partner-gated write
-- for staff) — no new RLS needed, identical justification to checklist_items.
--
-- filed_date is added alongside arn (not just arn alone) because the two are
-- captured together at the same completion step (see task-stage-panel.tsx's
-- existing two-input form) and a client confirmation ("Filed on 15 Aug 2026,
-- ARN XXXXXXXX") needs both — promoting only one of a tightly-coupled pair
-- would be an arbitrary split.
--
-- The existing task_activities `filing_outcome_recorded` log entry is KEPT
-- (not removed) — it remains the audit-trail record of the event (who/when),
-- while the new columns become the source of truth for DISPLAY (grid,
-- portal, task detail). No behavior change for the activity feed.
--
-- ----------------------------------------------------------------------------
-- Part B — udin_register (new table)
-- ----------------------------------------------------------------------------
-- ROADMAP.md Phase 12.5: "UDIN register: capture only, NOT auto-generated.
-- Fields: udin, document type, client, date, signing partner, linked task/
-- document. ICAI portal integration is out of scope." A UDIN (Unique
-- Document Identification Number) is generated by a signing CA member on
-- ICAI's own UDIN portal for every audit report, certificate, or attestation
-- they sign — this table is purely a firm-side RECORD of that fact, not a
-- generator or validator against ICAI's systems.
--
-- Design notes:
--   - firm_id + client_id: firm-scoped register, one row per certified
--     document/UDIN. client_id is NOT NULL — every real UDIN in CA practice
--     is issued against a specific client's document; RESTRICT (not
--     CASCADE), same as tasks.client_id — a statutory record must never be
--     cascade-deleted by a client removal (clients have no DELETE policy
--     anyway, F6).
--   - udin: ICAI UDINs are always exactly 18 alphanumeric characters. The
--     CHECK validates only that (length + charset), not the internal
--     year/membership-number/serial sub-structure — that encoding isn't a
--     stable enough public spec to hardcode into a CHECK constraint without
--     risk of rejecting a genuine future-format UDIN.
--   - document_type: kept as free TEXT (non-empty), not a CHECK-constrained
--     enum. Unlike e.g. receipts.mode (a small, genuinely fixed set of
--     payment rails), the CA-practice taxonomy of "what a UDIN document is"
--     varies by firm and engagement (tax audit report, GST audit report,
--     net worth certificate, various non-assurance certificates, ...) — a
--     hardcoded enum risked inventing categories that don't map to how a
--     given firm actually files, which project_context.md's brief for this
--     phase explicitly warned against ("don't invent fields that don't map
--     to how UDINs are actually used").
--   - signing_partner_id: the CA member who generated the UDIN on ICAI's
--     portal. References profiles(id) with NO role restriction at the DB
--     layer (deliberate: this schema's role model only distinguishes
--     partner/employee/client_user, not "holds a Certificate of Practice" —
--     an employee could, in principle, be the actual signing member on a
--     document). The app layer defaults the picker to partners (the
--     practical common case) without hard-blocking an employee selection a
--     firm might legitimately need.
--   - task_id / document_id: OPTIONAL links (ON DELETE SET NULL) to the
--     originating statutory task and/or the certified document — a UDIN
--     register entry is a durable historical fact and must outlive either
--     if one is later deleted/detached, same reasoning as documents.task_id
--     already being SET NULL (§6/schema.sql "documents outlive tasks").
--   - No is_active / soft-delete column: unlike clients/departments/
--     compliance_types/fee_masters, a UDIN register entry isn't something a
--     firm "retires" — it's a point-in-time historical fact (a UDIN was
--     generated on ICAI's portal on a specific date; that either happened or
--     it was a data-entry mistake needing correction/removal). Partner-only
--     UPDATE/DELETE (below) covers correcting a typo or removing a mistaken
--     entry; no soft-delete concept maps to real usage here, so none was
--     added, per the same brief.
--   - UNIQUE (firm_id, udin): a real UDIN is globally unique (ICAI issues
--     each one once), but scoping the uniqueness constraint to firm_id
--     (rather than a bare global UNIQUE on udin) avoids a cross-tenant
--     constraint that could let one firm's insert attempt leak whether
--     another firm already holds a given UDIN (a duplicate-key error is
--     observable even under RLS, since the constraint is checked before
--     RLS-scoped visibility would otherwise hide the row) — same tenant-
--     isolation caution the rest of this schema follows throughout.
--
-- Permission gating (flagged as a finding, not decided unilaterally — see
-- the session report this migration shipped with): reads use the EXISTING
-- `reports.view` permission (identical gate to the filing-status grid this
-- register is adjacent to — no new permission key for reads). Writes
-- (INSERT/UPDATE/DELETE) are PARTNER-ONLY at the RLS layer itself (checked
-- via the existing get_user_role() helper, no permission-catalog key
-- involved) rather than inventing a new `compliance.manage`-style key —
-- mirrors Phase 10's identical choice for statutory-task generation
-- ("partner-only, not permission-gated... viewing is safely broader than
-- writing", project_context.md's decisions table). This was a judgment
-- call under an explicit "do NOT invent a new permission key without
-- flagging it as a finding" instruction; the alternative (a new
-- `compliance.manage` key paired with `reports.view` the same way
-- `billing.manage` pairs with `billing.view` per migration 006) remains
-- available later if a firm needs to delegate UDIN entry to non-partner
-- staff — deliberately not built preemptively.
--
-- Safety notes:
--   - Zero behavior change for existing rows: tasks.arn/filed_date are
--     nullable with no default constraint on existing data; udin_register is
--     a wholly new, empty table.
--   - No existing RLS policy is touched. No existing table is dropped or
--     narrowed.
--   - Not written to be idempotent (matches this project's existing
--     migration style) — intended to run ONCE.
--   - Apply as a single transaction (BEGIN/COMMIT, or the Supabase SQL
--     editor's implicit transaction).
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- Part A — tasks.arn / tasks.filed_date
-- ----------------------------------------------------------------------------

ALTER TABLE public.tasks
  ADD COLUMN arn        TEXT,
  ADD COLUMN filed_date DATE;

-- ----------------------------------------------------------------------------
-- Part B — udin_register
-- ----------------------------------------------------------------------------

CREATE TABLE public.udin_register (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  firm_id            UUID NOT NULL REFERENCES public.firms(id) ON DELETE CASCADE,
  client_id          UUID NOT NULL REFERENCES public.clients(id) ON DELETE RESTRICT,
  udin               TEXT NOT NULL CHECK (udin ~ '^[0-9A-Z]{18}$'),
  document_type      TEXT NOT NULL CHECK (length(trim(document_type)) > 0),
  generated_on       DATE NOT NULL DEFAULT CURRENT_DATE,
  signing_partner_id UUID NOT NULL REFERENCES public.profiles(id),
  task_id            UUID REFERENCES public.tasks(id) ON DELETE SET NULL,
  document_id        UUID REFERENCES public.documents(id) ON DELETE SET NULL,
  notes              TEXT,
  created_by         UUID NOT NULL REFERENCES public.profiles(id),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (firm_id, udin)
);

CREATE INDEX idx_udin_register_firm     ON public.udin_register(firm_id);
CREATE INDEX idx_udin_register_client   ON public.udin_register(client_id);
CREATE INDEX idx_udin_register_task     ON public.udin_register(task_id) WHERE task_id IS NOT NULL;
CREATE INDEX idx_udin_register_document ON public.udin_register(document_id) WHERE document_id IS NOT NULL;

CREATE TRIGGER on_udin_register_updated
  BEFORE UPDATE ON public.udin_register
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

ALTER TABLE public.udin_register ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Report viewers can see the UDIN register"
  ON public.udin_register FOR SELECT TO authenticated
  USING (firm_id = public.get_user_firm_id() AND public.has_permission('reports.view'));

CREATE POLICY "Super admins can view all UDIN register entries"
  ON public.udin_register FOR SELECT TO authenticated
  USING (public.is_super_admin());

CREATE POLICY "Partners can create UDIN register entries"
  ON public.udin_register FOR INSERT TO authenticated
  WITH CHECK (firm_id = public.get_user_firm_id() AND public.get_user_role() = 'partner');

CREATE POLICY "Partners can update UDIN register entries"
  ON public.udin_register FOR UPDATE TO authenticated
  USING (firm_id = public.get_user_firm_id() AND public.get_user_role() = 'partner');

CREATE POLICY "Partners can delete UDIN register entries"
  ON public.udin_register FOR DELETE TO authenticated
  USING (firm_id = public.get_user_firm_id() AND public.get_user_role() = 'partner');

-- No REVOKE-from-authenticated step needed here (unlike migrations 004/005's
-- views): Supabase's default-privileges gap that migration 005 closed only
-- applies to CREATE VIEW / bare CREATE TABLE without RLS; this is a normal
-- RLS-enabled table (RLS is the enforcement for every role, including
-- authenticated with no matching policy — default-deny).

COMMIT;

-- ============================================================================
-- ROLLBACK (reviewed, NOT run):
--
-- BEGIN;
-- DROP TABLE IF EXISTS public.udin_register;
-- ALTER TABLE public.tasks DROP COLUMN IF EXISTS filed_date;
-- ALTER TABLE public.tasks DROP COLUMN IF EXISTS arn;
-- COMMIT;
--
-- Dropping udin_register or tasks.arn/filed_date loses any data recorded
-- between apply and rollback (no other table holds a copy — the pre-
-- existing task_activities filing_outcome_recorded entries are unaffected
-- and remain the historical audit trail either way).
-- ============================================================================
