'use server';

import { getAuthProfile } from '@/lib/auth';
import type { ActionResultWithData } from '@/lib/types';

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/**
 * Server Action: invite a client contact to the portal.
 *
 * Inserts into client_portal_invitations — the token is generated by the
 * column default (gen_random_bytes) and read back. The insert uses the
 * USER-scoped client, so the RLS policy ("Client managers can create portal
 * invitations": clients.manage permission + same-firm client) is the real
 * gate; the app-layer checks below are defense-in-depth, matching the
 * DeadlineTracker convention.
 *
 * Email delivery is a console.log stub until Resend is wired — the invite
 * URL is also returned so a future UI can offer copy-to-clipboard.
 */
export async function inviteClientUserAction(
  clientId: string,
  email: string
): Promise<ActionResultWithData<{ inviteUrl: string }>> {
  const trimmedEmail = email?.trim().toLowerCase();

  if (!clientId || !trimmedEmail) {
    return { success: false, error: 'Client and email are required.' };
  }
  if (!EMAIL_RE.test(trimmedEmail)) {
    return { success: false, error: 'Please enter a valid email address.' };
  }

  const { supabase, userId, profile } = await getAuthProfile();

  // Defense-in-depth: partner, or employee with the clients.manage permission
  // (resolved by the same SECURITY DEFINER function the RLS policies use).
  if (profile.role !== 'partner') {
    const { data: allowed } = await supabase.rpc('has_permission', {
      p_key: 'clients.manage',
    });
    if (allowed !== true) {
      return { success: false, error: 'You do not have permission to invite clients.' };
    }
  }

  // RLS-scoped read: resolves only if the client belongs to this firm and is
  // visible to this user.
  const { data: client } = await supabase
    .from('clients')
    .select('id, name')
    .eq('id', clientId)
    .single();

  if (!client) {
    return { success: false, error: 'Client not found.' };
  }

  const { data: invitation, error: insertError } = await supabase
    .from('client_portal_invitations')
    .insert({
      firm_id: profile.firm_id,
      client_id: clientId,
      email: trimmedEmail,
      invited_by: userId,
    })
    .select('token')
    .single();

  if (insertError || !invitation) {
    console.error('inviteClientUserAction insert error:', insertError);
    return { success: false, error: 'Failed to create the invitation. Please try again.' };
  }

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000';
  const inviteUrl = `${siteUrl}/portal/accept-invite?token=${invitation.token}`;

  // TODO(resend): replace this stub with a real invitation email once Resend
  // is wired up. Until then the URL is logged server-side and returned to the
  // caller for manual delivery.
  console.log(
    `[client-invite] Portal invitation for ${trimmedEmail} (client "${client.name}"): ${inviteUrl}`
  );

  return { success: true, data: { inviteUrl } };
}
